# Generated by Django 3.2.12 on 2022-05-24 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PropertyServiceApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentadvice',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PropertyServiceApp.users'),
        ),
        migrations.AlterField(
            model_name='legalissues',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PropertyServiceApp.users'),
        ),
        migrations.AlterField(
            model_name='maintainanceandlease',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PropertyServiceApp.users'),
        ),
        migrations.AlterField(
            model_name='otherservices',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PropertyServiceApp.users'),
        ),
        migrations.AlterField(
            model_name='propertymonitoring',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PropertyServiceApp.users'),
        ),
        migrations.AlterField(
            model_name='propertytracing',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PropertyServiceApp.users'),
        ),
    ]
