# Generated by Django 3.2.12 on 2022-05-07 19:45

import PropertyServiceApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PropertyServiceApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertytracing',
            name='sno',
            field=models.IntegerField(default=PropertyServiceApp.models.pt_records_count),
        ),
    ]
