# Generated by Django 3.2.12 on 2022-05-07 20:35

import PropertyServiceApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PropertyServiceApp', '0002_propertytracing_sno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintainanceandlease',
            name='id',
        ),
        migrations.AddField(
            model_name='maintainanceandlease',
            name='service_id',
            field=models.CharField(default=PropertyServiceApp.models.create_maintainaceLease_servId, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='maintainanceandlease',
            name='sno',
            field=models.IntegerField(default=PropertyServiceApp.models.ml_records_count),
        ),
    ]
