# Generated by Django 3.2.12 on 2022-05-12 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PropertyServiceApp', '0004_auto_20220508_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentadvice',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PropertyServiceApp.users'),
        ),
        migrations.AddField(
            model_name='legalissues',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PropertyServiceApp.users'),
        ),
        migrations.AddField(
            model_name='maintainanceandlease',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PropertyServiceApp.users'),
        ),
        migrations.AddField(
            model_name='otherservices',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PropertyServiceApp.users'),
        ),
        migrations.AddField(
            model_name='propertymonitoring',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PropertyServiceApp.users'),
        ),
        migrations.AddField(
            model_name='propertytracing',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='PropertyServiceApp.users'),
        ),
    ]
