# Generated by Django 3.2.12 on 2022-04-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PropertyServiceApp', '0004_alter_users_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='address',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
