# Generated by Django 3.2.12 on 2022-05-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PropertyServiceApp', '0005_alter_users_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyTracing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_title', models.CharField(max_length=255)),
                ('property_type', models.CharField(max_length=55)),
                ('property_description', models.CharField(blank=True, max_length=255, null=True)),
                ('available_days', models.JSONField()),
                ('available_time', models.JSONField()),
            ],
        ),
    ]
