# Generated by Django 3.2.12 on 2022-05-02 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PropertyServiceApp', '0006_propertytracing'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertytracing',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='PropertyServiceApp.users'),
        ),
    ]
