# Generated by Django 3.2.12 on 2022-05-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PropertyServiceApp', '0008_auto_20220502_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertytracing',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
