# Generated by Django 3.2.12 on 2022-05-03 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PropertyServiceApp', '0009_alter_propertytracing_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertytracing',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='PropertyServiceApp.users'),
        ),
    ]
