# Generated by Django 3.2.12 on 2022-05-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PropertyServiceApp', '0012_auto_20220505_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertytracing',
            name='available_days',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertytracing',
            name='available_time',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertytracing',
            name='property_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='propertytracing',
            name='property_type',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
