# Generated by Django 3.2.12 on 2022-05-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PropertyServiceApp', '0013_auto_20220505_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertytracing',
            name='available_days',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertytracing',
            name='available_time',
            field=models.TextField(blank=True, null=True),
        ),
    ]
