# Generated by Django 3.2.12 on 2022-05-06 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PropertyServiceApp', '0015_auto_20220505_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintainanceAndLease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_title', models.CharField(blank=True, max_length=255, null=True)),
                ('property_type', models.CharField(blank=True, max_length=55, null=True)),
                ('property_description', models.CharField(blank=True, max_length=255, null=True)),
                ('video', models.TextField(blank=True, null=True)),
                ('virtual_tour', models.TextField(blank=True, null=True)),
                ('available_days', models.JSONField(blank=True, null=True)),
                ('available_time', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='maintainance_and_lease', to='PropertyServiceApp.users')),
            ],
        ),
    ]
