# Generated by Django 3.2.12 on 2022-05-06 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PropertyServiceApp', '0017_legalissues'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monitoring_type', models.CharField(blank=True, max_length=255, null=True)),
                ('property_type', models.CharField(blank=True, max_length=55, null=True)),
                ('property_description', models.CharField(blank=True, max_length=255, null=True)),
                ('available_days', models.JSONField(blank=True, null=True)),
                ('available_time', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='property_monitoring', to='PropertyServiceApp.users')),
            ],
        ),
    ]
